name: fgmk
version: 0.1.0
summary: a tool similar to old rpgmaker
description: |
 FGMK is a tool to help you create a 2D top down RPG game that runs
 on a browser.

icon: icon.png
confinement: strict

apps:
  fgmk:
    command: fgmk

parts:
  fgmk:
    plugin: python3
    source: git://github.com/ericoporto/fgmk
    source-type: git
    python-packages:
      - numpy
      - pillow
    build-packages: [libjpeg-dev]
    stage-packages:
      - python3-pyqt5
      - python3-pyqt5.qtwebkit
      - libc-bin
      - locales
